apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: app-ingress
spec:
  rules:
  - host: next-app-server
    http:
      paths:
      - backend:
          serviceName: app-service
          servicePort: 80

---
kind: Service
apiVersion: v1
metadata:
  name: app-service
spec:
  type: NodePort
  selector:
    app: web
  ports:
  - port: 80
    targetPort: 3000

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-deployment-test
spec:
  replicas: 2
  selector:
    matchLabels:
      app: web
      version: test
  template:
    metadata:
      labels:
        app: web
        version: test
    spec:
      containers:
      - image: quanwei/next-app:test
        name: next-app
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 3000
